alca-app/src/components/ConnectWeb3Button.jsx, alca-app/src/components/HelpDropdown.jsx, alca-app/src/components/NavigationBar.jsx, alca-app/src/components/index.js, alca-app/src/config/_config.js, alca-app/src/pages/Transactions/Transactions.jsx
=> feat: add help button, fix menu items

alca-lockup/src/eth/ethAdapter.js, alca-lockup/src/redux/actions/application.js, alca-migrate/src/components/alcaCalculator/AlcaCalculator.jsx, alca-migrate/src/eth/ethAdapter.js, alca-migrate/src/redux/actions/application.js, alca-staking/src/eth/ethAdapter.js, alca-staking/src/redux/actions/application.js
=> Fix/alca app/config imports

alca-app/src/components/NavigationBar.jsx, alca-app/src/pages/Transactions/Transactions.jsx
=> Feat/alca app/full width migrate

alca-app/src/pages/Positions/Positions.jsx
https://github.com/alicenet/ui/issues/75
=> Hide empty locked positions

alca-app/src/pages/Positions/Positions.jsx
Resolve https://github.com/alicenet/ui/issues/70
=> feat: staked positions

alca-app/src/components/SnackbarMessage.jsx, alca-app/src/pages/Positions/Positions.jsx, alca-app/src/pages/Transactions/Transactions.jsx
Resolves https://github.com/alicenet/ui/issues/72
Resolves https://github.com/alicenet/ui/issues/71
=> feat: unstake position

alca-app/src/pages/Transactions/Transactions.jsx
Resolves https://github.com/alicenet/ui/issues/111
=> feat: disable lock when position exists

alca-app/src/components/ConnectWeb3Button.jsx
Resolves https://github.com/alicenet/ui/issues/105
=> feat: show error message if connect fails

alca-app/src/pages/Positions/Positions.jsx, alca-app/src/pages/Transactions/Transactions.jsx
=> chore: hide pagination for lockup position datagrid

alca-app/src/pages/Positions/Positions.jsx, alca-app/src/pages/Transactions/Transactions.jsx, alca-app/src/utils/string.js, alca-staking/src/utils/constants.js
=> feat: add utility to check allowed input characters

alca-app/src/components/LanderHelpModal.jsx
https://github.com/alicenet/ui/issues/109
=> feat: help modal navigation

alca-app/src/components/CountBubble.jsx, alca-app/src/components/SubNavigation.jsx, alca-app/src/pages/Positions/Positions.jsx
Resolves https://github.com/alicenet/ui/issues/128
=> feat: count bubble for sub nav positions

alca-app/src/components/NavigationBar.jsx, alca-app/src/components/SubNavigation.jsx, alca-app/src/pages/Positions/Positions.jsx, alca-app/src/pages/Transactions/Transactions.jsx, alca-app/src/theme/MUITheme.js
=> Chore/alca app/integrate mui provider

alca-app/src/pages/Transactions/Transactions.jsx
https://github.com/alicenet/ui/issues/124
=> feat: add tooltip to staking fields

alca-app/src/components/LanderHelpModal.jsx
Resolves https://github.com/alicenet/ui/issues/136
=> feat: add ToS to help modal

alca-app/src/pages/Transactions/Transactions.jsx
Resolves https://github.com/alicenet/ui/issues/154
=> feat: check if mad amount is over balance

alca-app/src/components/ConfirmUnstakeModal.jsx
=> fix: add zero rewards message

alca-app/src/pages/Transactions/Transactions.jsx
=> Remove elevation from Transactions title

alca-app/src/components/PositionsTabPanel.jsx, alca-app/src/components/PositionsTabs.jsx, alca-app/src/components/index.js
I had added an extra step before finally removing the inline styling.
=> Extract Position Tab Panels

alca-app/yarn.lock, package.json, yarn.lock
Also works for us to test Netlify issues
=> Testing removing postinstall scripts

packages/alca-app/src/pages/Transactions/Transactions.jsx
=> @kind/bug - Staking table is misaligned
